### ISSUE TITLE
Command failed with exit code 1. on Yarn run

### ISSUE THREAD

**Issue by lloydrayner** [zenetio/Install-VScode-On-TX2#1]
Hi, 

Im running on the TX2 and get an error at the '7. Install dependencies using yarn tool' section. 

Any help you can provide would be greatly appreciated. 

Thank you

warning package.json: No license field
warning vscode-reh@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "vscode-fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.1.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.1: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
[4/4] Building fresh packages...
[1/6] ⠈ native-watchdog
[2/6] ⠈ node-pty
[3/6] ⠈ nsfw
[4/6] ⠈ spdlog
error /home/nvidia/vscode/remote/node_modules/spdlog: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/nvidia/vscode/remote/node_modules/spdlog
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.16.1 | linux | arm64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nvidia/vscode/remote/node_modules/spdlog/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/nvidia/.node-gyp/10.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/nvidia/.node-gyp/10.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/nvidia/.node-gyp/10.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/nvidia/vscode/remote/node_modules/spdlog',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: name 'build_v8_with_gn' is not defined while evaluating condition 'build_v8_with_gn == "true"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.38-tegra
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nvidia/vscode/remote/node_modules/spdlog
gyp ERR! node -v v8.16.1

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by zenetio** [comment]
@lloydrayner I double checked the steps and did find a typo in step #6. Please take a look and see if it fix the issue.
Cheers.

**Comment by botmayank** [comment]
@zenetio Hi, I'm facing the same issue but in nsfw. I tried your latest instructions with the typo corrected.

```yarn
yarn install v1.17.3
$ node build/npm/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "vscode-fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.1.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.2: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-foreground-love@0.2.0: The platform "linux" is incompatible with this module.
info "windows-foreground-love@0.2.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-mutex@0.3.0: The platform "linux" is incompatible with this module.
info "windows-mutex@0.3.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info windows-process-tree@0.2.4: The platform "linux" is incompatible with this module.
info "windows-process-tree@0.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
[4/4] Building fresh packages...
success Saved lockfile.
$ node build/npm/postinstall.js
Installing dependencies in extensions...
$ yarn 
yarn install v1.17.3
warning package.json: No license field
warning vscode-extensions@0.0.1: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ node ./postinstall
Done in 0.42s.
Installing dependencies in remote...
$ yarn 
yarn install v1.17.3
warning package.json: No license field
warning vscode-reh@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info vscode-fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "vscode-fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-ca-certs@0.1.0: The platform "linux" is incompatible with this module.
info "vscode-windows-ca-certs@0.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info vscode-windows-registry@1.0.2: The platform "linux" is incompatible with this module.
info "vscode-windows-registry@1.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
[4/4] Building fresh packages...
[1/6] ⠠ native-watchdog
[2/6] ⠠ node-pty
[3/6] ⠠ nsfw
[4/6] ⠠ spdlog
error /home/mjtonbo/Documents/0_Setups/tools/vscode/remote/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/mjtonbo/Documents/0_Setups/tools/vscode/remote/node_modules/nsfw
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.16.1 | linux | arm64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mjtonbo/Documents/0_Setups/tools/vscode/remote/node_modules/nsfw/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mjtonbo/.node-gyp/10.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/mjtonbo/.node-gyp/10.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/mjtonbo/.node-gyp/10.11.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/mjtonbo/Documents/0_Setups/tools/vscode/remote/node_modules/nsfw',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: name 'build_v8_with_gn' is not defined while evaluating condition 'build_v8_with_gn == "true"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.140-tegra
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mjtonbo/Documents/0_Setups/tools/vscode/remote/node_modules/nsfw




error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by botmayank** [comment]
I found a reference to the flag in https://github.com/prebuild/prebuildify/issues/10 but I don't know which is the exact ./configure command is to pass this flag.

**Comment by zenetio** [comment]
@botmayank Hi, I am not sure what you did but it seems that you executed the yarn command more than once and, as what I can see, the first time it worked. Have you tried to execute the step #8? 
Cheers.

**Comment by botmayank** [comment]
Step #8 gives this: 

```yarn run v1.17.3
$ gulp watch --max_old_space_size=4095
[10:27:11] Node flags detected: --max_old_space_size=4095
[10:27:11] Respawned to PID: 9616
module.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-bom'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mjtonbo/Documents/0_Setups/tools/vscode/build/lib/compilation.js:10:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Also, in my previous logs, I ran yarn only once <logs start after my command not included in prev post>, the other $yarn's that you see are printed automatically and it still fails with the same log.

**Comment by zenetio** [comment]
@botmayank Have you fixed the issue? I just installed VS Code in TX2 board and in my Ubuntu laptop using this same process.
